/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.ZoneId;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import poo.javabnb.Inmuebles;
import poo.javabnb.UtilInmuebles;
import poo.javabnb.Clientes;

/**
 *
 * @author Alejandro
 */
public class DatosInmu extends javax.swing.JFrame {
    
    private Clientes cli;
    private BufferedImage foto = null;
    /**
     * Creates new form DatosInmuebles
     * @param cli
     */
    public DatosInmu(Clientes cli) {
        this.cli = cli;
        initComponents();
    }
    
    public DatosInmu() {
        initComponents();
    }

    //metodos para devolver y presentar el contenido de los campos del formulario
    public String getJTextFieldTitulo() {
        return jTextFieldTitulo.getText();
    }

    public String getJTextFieldCalle() {
        return jTextFieldCalle.getText();
    }

    public String getJTextFieldNumero() {
        return jTextFieldNumero.getText();
    }

    public String getJTextFieldCodigoPostal() {
        return jTextFieldCodigoPostal.getText();
    }

    public String getJTextFieldCiudad() {
        return jTextFieldCiudad.getText();
    }

    public String getJTextFieldNumHuespedes() {
        return jTextFieldNumHuespedes.getText();
    }

    public String getJTextFieldNumHabitaciones() {
        return jTextFieldNumHabitaciones.getText();
    }

    public String getJTextFieldNumCamas() {
        return jTextFieldNumCamas.getText();
    }

    public String getJTextFieldNumBanos() {
        return jTextFieldNumBanos.getText();
    }

    public String getComboBoxTipoPropiedad() {
        return String.valueOf(jComboBoxTipoPropiedad.getSelectedItem());
    }

    public String getJFormattedTextFieldPrecioNkche() {
        return jFormattedTextFieldPrecioNkche.getText();
    }

    public String getComboBoxCalificacion() {
        return String.valueOf(jComboBoxCalificacion.getSelectedItem());
    }

    public String getJTextFieldServicios() {
        return jTextFieldServicios.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonCrearInmueble = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldCalle = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldCodigoPostal = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jTextFieldNumHuespedes = new javax.swing.JTextField();
        jTextFieldNumHabitaciones = new javax.swing.JTextField();
        jTextFieldNumCamas = new javax.swing.JTextField();
        jTextFieldNumBanos = new javax.swing.JTextField();
        jComboBoxCalificacion = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldServicios = new javax.swing.JTextField();
        jComboBoxTipoPropiedad = new javax.swing.JComboBox<>();
        jFormattedTextFieldPrecioNkche = new javax.swing.JFormattedTextField();
        jButtonFoto = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 220, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lao MN", 2, 18)); // NOI18N
        jLabel1.setText("DATOS DEL INMUEBLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 210, 30));

        jLabel2.setText("Titulo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 37, -1));

        jLabel3.setText("Calle");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 37, -1));

        jLabel4.setText("Número");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 50, 20));

        jLabel5.setText("Codigo Postal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel6.setText("Ciudad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel7.setText("Número de huespedes");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel8.setText("Número de habitaciones");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jLabel9.setText("Tipo de propiedad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, 20));

        jLabel10.setText("Número de baños");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        jLabel11.setText("Precio por noche");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, -1, -1));

        jLabel12.setText("Número de camas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        jLabel13.setText("Calificación");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, -1, -1));

        jButtonCrearInmueble.setText("Crear inmueble");
        jButtonCrearInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCrearInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 720, -1, -1));

        jLabel14.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel14.setText("Dirección");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel15.setText("Especificaciones inmueble");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        jLabel16.setText("Características");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));
        jPanel1.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 270, 20));
        jPanel1.add(jTextFieldCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 160, 20));
        jPanel1.add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 160, 20));
        jPanel1.add(jTextFieldCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 160, 20));
        jPanel1.add(jTextFieldCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 160, 20));
        jPanel1.add(jTextFieldNumHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 160, 20));
        jPanel1.add(jTextFieldNumHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 160, 20));
        jPanel1.add(jTextFieldNumCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 160, 20));
        jPanel1.add(jTextFieldNumBanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 160, 20));

        jComboBoxCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCalificacionActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 110, 20));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, -1, -1));

        jLabel17.setText("Servicios");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, -1, -1));

        jTextFieldServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 170, 20));

        jComboBoxTipoPropiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", " " }));
        jPanel1.add(jComboBoxTipoPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, -1, -1));

        jFormattedTextFieldPrecioNkche.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldPrecioNkche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPrecioNkcheActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldPrecioNkche, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 600, 170, 20));

        jButtonFoto.setText("Insertar foto");
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jLabel18.setText("Inserte la foto del inmueble que desea registrar ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        lblFoto.setText("jLabel19");
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 190, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCalificacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServiciosActionPerformed

    private void jButtonCrearInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearInmuebleActionPerformed
        try {
        String titulo = getJTextFieldTitulo();
        String calle = getJTextFieldCalle();
        String numero = getJTextFieldNumero();
        String codigoPostal = getJTextFieldCodigoPostal();
        String ciudad = getJTextFieldCiudad();
        String numHuespedes = getJTextFieldNumHuespedes();
        String numHabitaciones = getJTextFieldNumHabitaciones();
        String numCamas = getJTextFieldNumCamas();
        String numBanos = getJTextFieldNumBanos();
        String tipoPropiedad = getComboBoxTipoPropiedad();
        double precioNoche = Double.parseDouble(getJFormattedTextFieldPrecioNkche());
        double calificacion = Double.parseDouble(getComboBoxCalificacion());
        String servicios = getJTextFieldServicios();

        Inmuebles inmueble = new Inmuebles(titulo, calle, numero, codigoPostal, ciudad, numHuespedes, numHabitaciones, numCamas, numBanos, tipoPropiedad, precioNoche, calificacion, servicios,cli.getCorreo());
        if(UtilInmuebles.registrarInmueble(inmueble)){
            JOptionPane.showMessageDialog(this, "Inmueble registrado en la app", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el inmueble en la app", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Excepción al registrar el inmueble", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCrearInmuebleActionPerformed

    private void jFormattedTextFieldPrecioNkcheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPrecioNkcheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPrecioNkcheActionPerformed

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
    JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                }
                String name = f.getName().toLowerCase();
                return name.endsWith(".png") || name.endsWith(".jpg") || name.endsWith(".jpeg");
            }

            @Override
            public String getDescription() {
                return "Image Files (PNG, JPEG)";
            }
        });

        int option = fileChooser.showOpenDialog(DatosInmu.this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                foto = ImageIO.read(selectedFile); // Load the image into the BufferedImage
                Image scaledImage = foto.getScaledInstance(250, 77, Image.SCALE_SMOOTH); // Scale the image
                ImageIcon imageIcon = new ImageIcon(scaledImage); // Use the scaled image to create an ImageIcon
                lblFoto.setIcon(imageIcon);

            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(DatosInmu.this, "Error loading image", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosInmu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosInmu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosInmu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosInmu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosInmu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCrearInmueble;
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JComboBox<String> jComboBoxCalificacion;
    private javax.swing.JComboBox<String> jComboBoxTipoPropiedad;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioNkche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldCodigoPostal;
    private javax.swing.JTextField jTextFieldNumBanos;
    private javax.swing.JTextField jTextFieldNumCamas;
    private javax.swing.JTextField jTextFieldNumHabitaciones;
    private javax.swing.JTextField jTextFieldNumHuespedes;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldServicios;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables
}
