/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Alejandro
 */
public class ModifiDatosCliParti extends javax.swing.JFrame {

    /**
     * Creates new form DatosCliParti2
     */
    public ModifiDatosCliParti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModDNI = new javax.swing.JTextField();
        txtModNombre = new javax.swing.JTextField();
        txtModCorreo = new javax.swing.JTextField();
        txtModClave = new javax.swing.JTextField();
        txtModTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtModNombreTarjetaCredito = new javax.swing.JTextField();
        formattedTxtModFechaCaducidadTarjeta = new javax.swing.JFormattedTextField();
        txtModNumeroTarjeta = new javax.swing.JTextField();
        buttonModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        RadioButtonModVIP = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 220, 186));
        jPanel1.setForeground(new java.awt.Color(255, 214, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("MODIFICACIÓN DATOS CLIENTES PARTICULARES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setText("DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 64, 37, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 105, -1, -1));

        jLabel4.setText("Correo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 146, 74, -1));

        jLabel5.setText("Clave");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 187, 37, -1));

        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 225, -1, -1));
        jPanel1.add(txtModDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 61, 71, -1));
        jPanel1.add(txtModNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 102, 71, -1));
        jPanel1.add(txtModCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 143, 71, -1));
        jPanel1.add(txtModClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 184, 71, -1));
        jPanel1.add(txtModTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 225, 71, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tarjeta de Crédito");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 261, -1, -1));

        jLabel8.setText("Nombre del Titular");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 293, -1, -1));

        jLabel9.setText("Fecha de Caducidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 334, -1, -1));

        jLabel10.setText("Número");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 375, -1, -1));
        jPanel1.add(txtModNombreTarjetaCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 290, 71, -1));
        jPanel1.add(formattedTxtModFechaCaducidadTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 331, 126, -1));
        jPanel1.add(txtModNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 372, 71, -1));

        buttonModificar.setText("Modificar");
        jPanel1.add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 465, -1, -1));

        jLabel11.setText("VIP");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 415, 43, -1));

        RadioButtonModVIP.setText("Si, soy un cliente VIP");
        RadioButtonModVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonModVIPActionPerformed(evt);
            }
        });
        jPanel1.add(RadioButtonModVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 413, 150, 30));

        jLabel12.setText("En esta pestaña, si lo desea puede modificar sus datos ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonModVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonModVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonModVIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifiDatosCliParti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonModVIP;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JFormattedTextField formattedTxtModFechaCaducidadTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtModClave;
    private javax.swing.JTextField txtModCorreo;
    private javax.swing.JTextField txtModDNI;
    private javax.swing.JTextField txtModNombre;
    private javax.swing.JTextField txtModNombreTarjetaCredito;
    private javax.swing.JTextField txtModNumeroTarjeta;
    private javax.swing.JTextField txtModTelefono;
    // End of variables declaration//GEN-END:variables
}
