/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Alejandro
 */
public class ModifiDatosAnfitriones extends javax.swing.JFrame {

    /**
     * Creates new form DatosAnfitriones
     */
    public ModifiDatosAnfitriones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModDNI = new javax.swing.JTextField();
        txtModNombre = new javax.swing.JTextField();
        txtModCorreo = new javax.swing.JTextField();
        txtModClave = new javax.swing.JTextField();
        txtModTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        formattedTxtModFechaRegistro = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        buttonModificar = new javax.swing.JButton();
        comboBoxModCalificacion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 220, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("MODIFICACIÓN DATOS ANFITRIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 33, -1, -1));

        jLabel2.setText("DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 71, 37, -1));

        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 112, -1, -1));

        jLabel4.setText("Correo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 158, 37, -1));

        jLabel5.setText("Clave");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 204, 37, -1));

        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 250, -1, -1));
        jPanel1.add(txtModDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 71, -1));
        jPanel1.add(txtModNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 109, 71, -1));
        jPanel1.add(txtModCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 155, 71, -1));

        txtModClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModClaveActionPerformed(evt);
            }
        });
        jPanel1.add(txtModClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 201, 71, -1));
        jPanel1.add(txtModTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 247, 71, -1));

        jLabel7.setText("Fecha de Registro");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 297, -1, -1));

        formattedTxtModFechaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTxtModFechaRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(formattedTxtModFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 294, 126, -1));

        jLabel8.setText("Calificación");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 344, -1, -1));

        buttonModificar.setText("Modificar");
        jPanel1.add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 394, -1, -1));

        comboBoxModCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(comboBoxModCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 341, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModClaveActionPerformed

    private void formattedTxtModFechaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTxtModFechaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTxtModFechaRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifiDatosAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifiDatosAnfitriones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JComboBox<String> comboBoxModCalificacion;
    private javax.swing.JFormattedTextField formattedTxtModFechaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtModClave;
    private javax.swing.JTextField txtModCorreo;
    private javax.swing.JTextField txtModDNI;
    private javax.swing.JTextField txtModNombre;
    private javax.swing.JTextField txtModTelefono;
    // End of variables declaration//GEN-END:variables
}
