/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Alejandro
 */
public class OperacionesAnfitriones extends javax.swing.JFrame {

    /**
     * Creates new form OperacionesAnfitriones
     */
    public OperacionesAnfitriones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarInmueble = new javax.swing.JButton();
        jButtonAdministrarInmueble = new javax.swing.JButton();
        jButtonReservasInmueble = new javax.swing.JButton();
        jButtonDatosPersonales = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 220, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Anfitriones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 35, -1, -1));

        jButtonRegistrarInmueble.setText("Registrar Inmueble");
        jButtonRegistrarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrarInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 149, -1, -1));

        jButtonAdministrarInmueble.setText("Administrar Inmuebles");
        jButtonAdministrarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdministrarInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 149, -1, -1));

        jButtonReservasInmueble.setText("Reservas Inmuebles");
        jButtonReservasInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservasInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReservasInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 247, -1, -1));

        jButtonDatosPersonales.setText(" Datos personales");
        jButtonDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosPersonalesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 247, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("¿Que quieres realizar?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 102, -1, -1));

        jButtonVolver.setText("Volver");
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 368, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarInmuebleActionPerformed
        DatosInmu newframe = new DatosInmu();
        newframe.setVisible(true); //para que aparezca la nueva ventana 
        this.dispose(); //para que se cierre la ventana actual
    }//GEN-LAST:event_jButtonRegistrarInmuebleActionPerformed

    private void jButtonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosPersonalesActionPerformed
        ModifiDatosAnfitriones newframe = new ModifiDatosAnfitriones();
        newframe.setVisible(true); //para que aparezca la nueva ventana 
        this.dispose(); //para que se cierre la ventana actual
    }//GEN-LAST:event_jButtonDatosPersonalesActionPerformed

    private void jButtonAdministrarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarInmuebleActionPerformed
        AdministrarInmuAnfi newframe = new AdministrarInmuAnfi();
        newframe.setVisible(true); //para que aparezca la nueva ventana 
        this.dispose(); //para que se cierre la ventana actual
    }//GEN-LAST:event_jButtonAdministrarInmuebleActionPerformed

    private void jButtonReservasInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservasInmuebleActionPerformed
        ReservasInmuebles newframe = new ReservasInmuebles();
        newframe.setVisible(true); //para que aparezca la nueva ventana 
        this.dispose(); //para que se cierre la ventana actual
    }//GEN-LAST:event_jButtonReservasInmuebleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesAnfitriones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionesAnfitriones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministrarInmueble;
    private javax.swing.JButton jButtonDatosPersonales;
    private javax.swing.JButton jButtonRegistrarInmueble;
    private javax.swing.JButton jButtonReservasInmueble;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
