/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;
import poo.javabnb.Clientes;
/**
 *
 * @author Alejandro
 */
public class OperacionesCliParti extends javax.swing.JFrame {

    private Clientes cli;
    /**
     * Creates new form OperacionesCliParti
     * @param cli
     */
    public OperacionesCliParti(Clientes cli) {
        initComponents();
    }
    
    public OperacionesCliParti(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonBusquedaInmueble = new javax.swing.JButton();
        jButtonReservaInmueble = new javax.swing.JButton();
        jButtonResena = new javax.swing.JButton();
        jButtonDatosPersonales = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonMisReservas = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 220, 186));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Clientes Particulares");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jButtonBusquedaInmueble.setText("Búsqueda Inmuebles");
        jButtonBusquedaInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBusquedaInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 151, -1, -1));

        jButtonReservaInmueble.setText("Reserva Inmuebles");
        jButtonReservaInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservaInmuebleActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReservaInmueble, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 151, -1, -1));

        jButtonResena.setText("Reseña");
        jPanel1.add(jButtonResena, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 215, -1, -1));

        jButtonDatosPersonales.setText(" Datos personales");
        jButtonDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosPersonalesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 215, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("¿Que quieres realizar?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 106, -1, -1));

        jButtonMisReservas.setText("Mis reservas");
        jButtonMisReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisReservasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMisReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 272, -1, -1));

        jButtonVolver.setText("Volver");
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBusquedaInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBusquedaInmuebleActionPerformed

    private void jButtonReservaInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservaInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReservaInmuebleActionPerformed

    private void jButtonDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosPersonalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDatosPersonalesActionPerformed

    private void jButtonMisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMisReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliParti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionesCliParti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBusquedaInmueble;
    private javax.swing.JButton jButtonDatosPersonales;
    private javax.swing.JButton jButtonMisReservas;
    private javax.swing.JButton jButtonResena;
    private javax.swing.JButton jButtonReservaInmueble;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
